#!/usr/bin/env bash
#Author: github.com/NeshHari

# Set the output file path
OUTPUT_FILE="/tmp/last_window.txt"

# Get the current output
output=$(xprop -id $(xdotool getwindowfocus) WM_CLASS | grep -o '".*"' | cut -d '"' -f 2)
if [[ $output == steam_app_* ]]; then
	output=$(xprop -id $(xdotool getwindowfocus) WM_NAME | grep -o '".*"' | cut -d '"' -f 2)
fi
output=$(echo $output | sed 's/-/ /g' | sed -E 's/(^| )([a-z])/\1\u\2/g')

# Read the existing output from the output file
if [ -f "$OUTPUT_FILE" ]; then
	last_output=$(cat "$OUTPUT_FILE")
else
	last_output=""
fi

# Compare the current output with the last output and reload eww if they are different
if [ "$output" != "$last_output" ]; then
	echo "$output" >"$OUTPUT_FILE"
	eww close showfocusedclass
	eww open showfocusedclass
	eww close showfocusedclass
	eww open showfocusedclass
fi

if [ -z "$output" ]; then
	echo "Desktop"
else
	echo "$output"
fi

xdo lower -n eww-showfocusedclass
