#!/usr/bin/env python3
# Author: github.com/NeshHari

import random
import sys

quotes = [
    "Be the change you wish to see in the world. ~ Mahatma Gandhi",
    "I have a dream. ~ Martin Luther King Jr.",
    "Not all those who wander are lost. ~ J.R.R. Tolkien",
    "All that we see or seem is but a dream within a dream. ~ Edgar Allan Poe",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. ~ Ralph Waldo Emerson",
    "The only way to do great work is to love what you do. ~ Steve Jobs",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit. ~ Aristotle",
    "In three words I can sum up everything I've learned about life: it goes on. ~ Robert Frost",
    "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. ~ Helen Keller",
    "It does not matter how slowly you go as long as you do not stop. ~ Confucius",
    "Believe you can and you're halfway there. ~ Theodore Roosevelt",
    "The unexamined life is not worth living. ~ Socrates",
    "I know that I am intelligent, because I know that I know nothing. ~ Socrates",
    "In the end, we will remember not the words of our enemies, but the silence of our friends. ~ Martin Luther King Jr.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. ~ Winston Churchill",
    "You miss 100% of the shots you don't take. ~ Wayne Gretzky",
    "If you want to go fast, go alone. If you want to go far, go together. ~ African proverb",
    "You can't build a reputation on what you are going to do. ~ Henry Ford",
    "The only thing we have to fear is fear itself. ~ Franklin D. Roosevelt",
    "The journey of a thousand miles begins with one step. ~ Lao Tzu",
    "A house divided against itself cannot stand. ~ Abraham Lincoln",
    "Ask not what your country can do for you, ask what you can do for your country. ~ John F. Kennedy",
    "Life is a journey, and if you fall in love with the journey, you will be in love forever. ~ Peter Hagerty",
    "I am not a product of my circumstances. I am a product of my decisions. ~ Stephen Covey",
    "Our greatest glory is not in never falling, but in rising every time we fall. ~ Confucius",
    "Education is the most powerful weapon which you can use to change the world. ~ Nelson Mandela",
    "It always seems impossible until it's done. ~ Nelson Mandela",
    "The only true wisdom is in knowing you know nothing. ~ Socrates",
    "The best way to predict your future is to create it. ~ Abraham Lincoln",
]
last_quote = ""
quote = random.choice(quotes)
while quote == last_quote:
    quote = random.choice(quotes)
quote_parts = quote.split("~")
if len(sys.argv) >= 2:
    if sys.argv[1] == "--quote":
        print(quote_parts[0])
    if sys.argv[1] == "--bywho":
        print("~ " + quote_parts[1] + " ~")
last_quote = quote
