#!/usr/bin/env python3
# Author: github.com/NeshHari

import subprocess

cmd = ["/home/nesh/.config/xmonad/xmonad-contrib/scripts/xmonadpropread.hs"]
p = subprocess.Popen(cmd, stdout=subprocess.PIPE, text=True)

for line in p.stdout:
    if line.strip() == "Tall":
        print("")
    elif line.strip() == "BSP":
        print("")
    elif line.strip() == "Float":
        print("")
    elif line.strip() == "Full":
        print("")
    elif line.strip() == "Column":
        print("")
    elif line.strip() == "Accordion":
        print("")
    else:
        print(line.strip())
    p.kill()
    break

p.wait()
