-- local db = require('dashboard')
--
-- db.custom_header = {
--     [[ ███╗   ██╗ ███████╗ ██████╗  ██╗   ██╗ ██╗ ███╗   ███╗]],
--     [[ ████╗  ██║ ██╔════╝██╔═══██╗ ██║   ██║ ██║ ████╗ ████║]],
--     [[ ██╔██╗ ██║ █████╗  ██║   ██║ ██║   ██║ ██║ ██╔████╔██║]],
--     [[ ██║╚██╗██║ ██╔══╝  ██║   ██║ ╚██╗ ██╔╝ ██║ ██║╚██╔╝██║]],
--     [[ ██║ ╚████║ ███████╗╚██████╔╝  ╚████╔╝  ██║ ██║ ╚═╝ ██║]],
--     [[ ╚═╝  ╚═══╝ ╚══════╝ ╚═════╝    ╚═══╝   ╚═╝ ╚═╝     ╚═╝]],
-- }
--
-- db.custom_center = {
--     { icon = '  ',
--         desc = 'Find  File                              ',
--         action = 'Telescope find_files find_command=rg,--hidden,--files',
--         shortcut = 'SPC f f' },
--     { icon = '  ',
--         desc = 'File Browser                            ',
--         action = 'Telescope file_browser',
--         shortcut = 'SPC f b' },
--     { icon = '  ',
--         desc = 'Find Word                               ',
--         action = 'Telescope live_grep',
--         shortcut = 'SPC f w' },
--     { icon = '  ',
--         desc = 'Help                                    ',
--         action = 'Telescope help_tags',
--         shortcut = 'SPC f h' },
-- }
